`version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: proccess.env.MYSQL_PASSWORD
      MYSQL_DATABASE: proccess.env.MYSQL_DATABASE
      MYSQL_USER: proccess.env.MYSQL_USER
      MYSQL_PASSWORD: proccess.env.MYSQL_PASSWORD

  node-api:
    image: node:latest
    container_name: node-api-container
    volumes:
      - ./src:/api  # Substitua pelo caminho real do seu código
    working_dir: /api
    ports:
      - "3333:3333"  # Ajuste a porta conforme necessário
    depends_on:
      - mysql
    environment:
      DATABASE_URL: proccess.env.DATABASE_URL

    command: sh -c "npm install && npx prisma init && npx prisma migrate dev && npx prisma generate && npm start"  # Ajuste conforme necessário